### ISSUE TITLE
Request: Standalone drumsep option

### ISSUE THREAD

**Issue by AttaEaf** [IMF24/gh-demucs-gui#1]
Is it possible for there to be a way to use drumsep standalone (without normal demucs) from within the gui (say if one is using actual stems/multitracks and wants to split a single drums track into 4 parts without using the 4-stem demucs models first and thus not getting any superfluous bass/vocals/other stems)

**Comment by IMF24** [comment]
Yes, this would be possible. In a future update, I'll add this.
