### ISSUE TITLE
Exception when using 4 Lane Drums Stems w/ GH Track Names

### ISSUE THREAD

**Issue by AttaEaf** [IMF24/gh-demucs-gui#2]
So thanks for adding the standalone 4 lane stems as an option. However there the program spits out an exception when I use it with the
“Use Guitar Hero Track Names” setting. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "G:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\gh-demucs-gui-main\main.py", line 118, in split_audio
    OS.chdir(f"../../modelo_final/drums")
FileNotFoundError: [WinError 2] The system cannot find the file specified: '../../modelo_final/drums'

Apparently the program is trying to find a non-existent drums.wav file. For the record here are the actual names used by drumsep

bombo = drums_1, kick
redoblante = drums_2, snare
toms = drums_3, toms
platillos = drums_4, cymbals

Note that the drumsep works fine if the option is turned off.

**Comment by IMF24** [comment]
Thanks for bringing this to my attention. I will look into this and I should have it patched within a few hours.

**Comment by IMF24** [comment]
Try the latest commit for the program and see if you still receive this error. If you do, post the call stack (traceback) here and I'll look into it further.

**Comment by IMF24** [comment]
Almost 2 months inactive, assuming issue is resolved.
